import os
import stat
import sys

def install_hooks():
    # Check if .git directory exists
    git_dir = ".git"
    if not os.path.exists(git_dir):
        # Try looking one level up just in case
        if os.path.exists(os.path.join("..", ".git")):
            git_dir = os.path.join("..", ".git")
        else:
            print("Error: .git directory not found. Please run this script from the root of the git repository.")
            return

    hooks_dir = os.path.join(git_dir, "hooks")
    if not os.path.exists(hooks_dir):
        os.makedirs(hooks_dir)

    hook_path = os.path.join(hooks_dir, "pre-commit")
    
    # Shell script content for the hook
    # Using forward slashes for paths in shell script to ensure compatibility with Git Bash on Windows
    hook_content = """#!/bin/sh
# Auto-generated by scripts/setup_hooks.py

# Check if docs/openapi.yaml is staged
# We use git diff --cached to see what is about to be committed
if git diff --cached --name-only | grep -q "docs/openapi.yaml"; then
    echo "[Pre-commit] Detected change in openapi.yaml. Updating API documentation..."
    
    # Determine Python interpreter path
    # We try to find the venv python first
    if [ -f ".venv/Scripts/python.exe" ]; then
        PYTHON_CMD=".venv/Scripts/python.exe"
    elif [ -f ".venv/bin/python" ]; then
        PYTHON_CMD=".venv/bin/python"
    else
        PYTHON_CMD="python"
    fi
    
    # Run the update script
    "$PYTHON_CMD" scripts/update_docs.py
    
    # Check if script failed
    if [ $? -ne 0 ]; then
        echo "[Pre-commit] Error: Failed to update API documentation. Commit aborted."
        exit 1
    fi
    
    # Add the updated markdown file to the commit
    git add "docs/API仕様書.md"
    echo "[Pre-commit] Successfully updated and staged docs/API仕様書.md"
fi

exit 0
"""

    try:
        with open(hook_path, "w", encoding="utf-8", newline='\n') as f:
            f.write(hook_content)
        
        # Make the hook executable
        st = os.stat(hook_path)
        os.chmod(hook_path, st.st_mode | stat.S_IEXEC)
        
        print(f"Successfully installed pre-commit hook at: {hook_path}")
        print("Now, whenever you commit changes to 'docs/openapi.yaml', 'docs/API仕様書.md' will be automatically updated and included in the commit.")
        
    except Exception as e:
        print(f"Error installing hook: {e}")

if __name__ == "__main__":
    install_hooks()
